#! /bin/sh
#
# Example panel for lemonbar

. panel_colors

num_mon=$(bspc query -M | wc -l)
padd="  "

while read -r line ; do
	case $line in
		T*)
			# xtitle output
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
			;;
		S*)
			# clock output
			date="%{F$COLOR_DATE_FG}%{B$COLOR_DATE_BG} ${line#?} %{B-}%{F-}"
			;;
        B*)
            # battery level & wifi network output
            batt="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG} ${line#?} $padd %{B-}%{F-}"
            ;;
        N*)
            # wifi network output
            wifi="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG} ${line#?} $padd %{B-}%{F-}"
            ;;
		W*)
			# bspwm's state
			wm=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						[ $num_mon -lt 2 ] && shift && continue
						case $item in
							m*)
								# monitor
								FG=$COLOR_MONITOR_FG
								BG=$COLOR_MONITOR_BG
								;;
							M*)
								# focused monitor
								FG=$COLOR_FOCUSED_MONITOR_FG
								BG=$COLOR_FOCUSED_MONITOR_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[fFoOuU]*)
						case $item in
							[fo]*)
                                # free (& occupied free) desktop
								FG=$COLOR_FREE_FG
								BG=$COLOR_FREE_BG
								;;
							[FOU]*)
                                # focused free (& occupied free) desktop
								FG=$COLOR_FOCUSED_FREE_FG
								BG=$COLOR_FOCUSED_FREE_BG
								;;
							u*)
								# urgent desktop
								FG=$COLOR_URGENT_FG
								BG=$COLOR_URGENT_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${wm}%{c}${title}%{r}${batt}${wifi}${date}"
done
