[tools]

# languages and tooling
python = "latest"
rust = "latest"
ruff = "latest"
node = "lts"
uv = "latest"
opencode = "latest"
terraform = "latest"
pitchfork = "latest"
bun = "latest"

# general cli
ripgrep = "latest"
starship = "latest"
eza = "latest"
bat = "latest"
tmux = "latest"
difftastic = "latest"
"github:jnsahaj/lumen" = "latest"

# fuzzy finders and navigation
zoxide = "latest"
fzf = "latest"
television = "latest"
"github:wfxr/forgit" = "latest"


[hooks]
enter = "mise i -q"

[settings]
idiomatic_version_file_enable_tools = ["python"]
experimental = true

trusted_config_paths = [
  '~/git/',
  '~/.codex/worktrees/'
]
