[settings]
experimental = true
color_theme = "catppuccin"
idiomatic_version_file_enable_tools = ["python", "node"]
minimum_release_age = "3d"
trusted_config_paths = ['~/git/', '~/.codex/worktrees/', '~/.herder/worktrees/']

[tools]
# languages and tooling
python = "latest"
rust = "latest"
ruff = "latest"
node = "lts"
uv = "latest"
pi = { version = "latest", postinstall = "pi update --extensions" }
terraform = "latest"
pitchfork = "latest"

# containers
colima = "latest"
docker-cli = "latest"
lima = "latest"

# general cli
ripgrep = "latest"
starship = "latest"
eza = "latest"
bat = "latest"
tmux = "latest"
difftastic = "latest"

# fuzzy finders and navigation
zoxide = "latest"
fzf = "latest"
television = "latest"
"github:wfxr/forgit" = "latest"
"npm:@tobilu/qmd" = "latest"
"npm:agent-browser" = "latest"

# misc & unsorted

[hooks]
enter = "mise i -q"

[shell_alias]
ll = "eza -la --icons --group-directories-first"

[bootstrap.packages]
"brew:coreutils" = "latest"
"brew:zsh" = "latest"

[bootstrap.user]
login_shell = "/bin/zsh"

# MacOS specific configuration
[bootstrap.macos.dock]
autohide = true
orientation = "left"
tilesize = 48

[bootstrap.macos.finder]
show_pathbar = true

[bootstrap.macos.defaults]
"com.apple.finder" = { AppleShowAllFiles = true }
