# :schema https://mise.en.dev/schema/mise.json

[settings]
experimental = true
minimum_release_age = "3d"

dotfiles.root = "~/git/dotfiles"
dotfiles.default_mode = "symlink"

[dotfiles]
# Listing only directories & files to inherit, ignoring others that shouldn't be tracked (e.g. `~/.aws`)
"~/.config/mise/config.toml" = { source = ".config/mise/config.toml" }
"~/.config/ghostty" = { source = ".config/ghostty" }
"~/.config/herdr" = { source = ".config/herdr" }
"~/.config/tmux" = { source = ".config/tmux" }
"~/.config/zsh" = { source = ".config/zsh" }

# Oh-my-pi 
"~/.omp/agent/config.yml" = { source = ".omp/agent/config.yml" }

# Skills - NB: Some harnesses don't resolve symlinks.
"~/.agents/skills" = { source = "skills", mode = "copy" }
"~/.claude/skills" = { source = "skills", mode = "symlink-each" }

# Standalone files - sourced in ~/.config/ for organization, but symlinked to home
"~/.bash_profile" = { source = ".config/.bash_profile" }
"~/.inputrc" = { source = ".config/.inputrc" }
"~/.zshenv" = { source = ".config/.zshenv" }

# Avoid clashing with repo level Git config
"~/.gitconfig" = { source = "./.config/git/.gitconfig", mode = "symlink" }
"~/.gitignore" = { source = "./.config/git/.gitignore", mode = "symlink" }
