[character]
success_symbol = "[➜](bold green)"

[[battery.display]]
threshold = 25
style = "bold red"

[aws]
format = 'on[ ☁️ $profile (\[$duration\] )]($style)'

[kubernetes]
format = '[⛵ $context \($namespace\)](dimmed green) '
disabled = false
[kubernetes.context_aliases]
"qa-eu-a" = "qa"

[git_branch]
ignore_branches = ["master", "main"]

[nodejs]
format = "via [$version](bold green) "
disabled = false

[python]
disabled = true

[package]
disabled = true
