#! /bin/sh

bspc config border_width            2
bspc config window_gap              25
bspc config top_padding             25
bspc config split_ratio             0.50

bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config focus_follows_pointer   true

bspc config focused_border_color	'#4DB6AC'
bspc config urgent_border_color		'#dedede'

hsetroot -fill ~/Pictures/Wallpapers/1920x1080\ Teal.jpg

bspc monitor -d $(echo -e '\uf120') $(echo -e '\uf121') $(echo -e '\uf268') $(echo -e '\uf269') $(echo -e '\uf108')

bspc rule -a Chromium desktop=^3 follow=on
bspc rule -a Firefox desktop=^4 follow=on
bspc rule -a Atom desktop=^2 follow=on
bspc rule -a Gimp desktop=^5 follow=on floating=on

panel &
pulseaudio --start &
