[settings]
experimental = true
color_theme = "catppuccin"
idiomatic_version_file_enable_tools = ["python", "node"]
minimum_release_age = "3d"
trusted_config_paths = ['~/git/', '~/.codex/worktrees/', '~/.herdr/worktrees/']

[tools]
# languages and tooling
python = "latest"
rust = "latest"
ruff = "latest"
node = "lts"
uv = "latest"
terraform = "latest"
pitchfork = "latest"
gcloud = "latest"
github-cli = "latest"

# llm and ai
codex = "latest"
pi = { version = "latest", postinstall = "pi update --extensions" }
"github:can1357/oh-my-pi" = { version = "latest", postinstall = "omp update --plugins" }

# containers
colima = "latest"
docker-cli = "latest"
lima = "latest"

# general cli
ripgrep = "latest"
starship = "latest"
eza = "0.23.4"
fd = "latest"
bat = "latest"
tmux = "latest"
difftastic = "latest"

# fuzzy finders and navigation
zoxide = "latest"
fzf = "latest"
"github:wfxr/forgit" = "latest"

# misc & unsorted
"npm:@tobilu/qmd" = "latest"
"npm:agent-browser" = "latest"


[hooks]
enter = "mise i -q"

[tasks.gh-auth]
run = "gh auth status || gh auth login"

[shell_alias]
ll = "eza -la --icons --group-directories-first"

[bootstrap.repos]
"~/git/dotfiles" = { url = "git@github.com:ahstn/dotfiles.git", ref = "main" }
"~/.pi" = { url = "git@github.com:ahstn/pi.git", ref = "main" }

[bootstrap.packages]
# macOS
"brew:coreutils" = "latest"
"brew:weave" = "latest"
"brew:zsh" = "latest"
"brew-cask:keepingyouawake" = "latest"

# linux servers
"apt:curl" = "latest"
"apt:neovim" = "latest"
"apt:git" = "latest"
"apt:gcc" = "latest"
"apt:fzf" = "latest"
"apt:libfuse-dev" = "latest"
"apt:libssl-dev" = "latest"
"apt:zsh" = "latest"
"apt:rsync" = "latest"
"apt:ripgrep" = "latest"

[bootstrap.user]
login_shell = "/bin/zsh"

# MacOS specific configuration
[bootstrap.macos.dock]
autohide = true
orientation = "left"
tilesize = 48

[bootstrap.macos.finder]
show_pathbar = true
show_all_files = true

[bootstrap.macos.defaults]
"com.apple.finder" = { AppleShowAllFiles = true }

[bootstrap.hooks.post-defaults]
run = "killall Dock || true"
